[login]
m1 ansible_host=m1

[management]
m2 ansible_host=m2

[compute]
; regex match see: https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html#adding-ranges-of-hosts
; But below will parse each node's host as intern[1:100]
; compute[1:100] ansible_host=intern[1:100]
m3 ansible_host=m3 cpu=4 memory=6G partition="cpu_partition"
m4 ansible_host=m4 cpu=4 memory=6G partition="cpu_partition"
; g1 ansible_host=g1 cpu=4 memory=6G partition="gpu_partition" gres='{"name": "gpu", "type": "a100"}'

[compute:vars]
partitions='{"cpu_partition": {"name": "CPU", "priority": 5, "DefaultMemPerCpu": 0, "MaxMemPerCpu": 0}}'
; partitions='{"cpu_partition": {"name": "CPU", "priority": 5, "DefaultMemPerCpu": 0, "MaxMemPerCpu": 0}, "gpu_partition": {"name": "GPU", "priority": 3, "DefaultMemPerCpu": 0, "MaxMemPerCpu": 0, "AllowedAccounts": "ai-team"}}'

[all:vars]
disable_firewall=true
disable_security=true
frontend_path=/usr/local/bin

cluster_name=pkuhpc
crane_version=1.1.2

; Database
DbUser=admin
DbPassword="123456"
; Will install database if sets to 'localhost' or '127.0.0.1'
DbHost=127.0.0.1
DbPort=27017
DbReplSetName=crane_rs
DbName=crane_db