#!/usr/bin/env bash
# Paseo daemon one-shot deploy: install the CLI -> systemd --user service
# (enabled at boot) -> verify.
#
# Background: the Paseo GUI's Remote/SSH only connects to a daemon that is
# already running; it never installs, starts, or configures one remotely, and
# `paseo daemon start` merely detaches a background supervisor (writing
# ~/.paseo/paseo.pid and daemon.log) without registering boot autostart — so
# after a reboot nothing listens on 6767 again.
# This script follows the "user systemd manages the daemon" approach (the old
# install-user-daemon.sh from this repo was removed together with the old
# MaintainAll daemon): hand the daemon to systemd --user plus
# `loginctl enable-linger`, so crashes and reboots bring it back automatically.
#
# Env: PASEO_HOME (default ~/.paseo), PASEO_LISTEN_ADDR (default 127.0.0.1),
#      and PASEO_PORT (default 6767) override the readiness probe target.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
UNIT_NAME="paseo.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"
PASEO_HOME="${PASEO_HOME:-$HOME/.paseo}"
PID_FILE="$PASEO_HOME/paseo.pid"
LOG_FILE="$PASEO_HOME/daemon.log"
LISTEN_ADDR="${PASEO_LISTEN_ADDR:-127.0.0.1}"
LISTEN_PORT="${PASEO_PORT:-6767}"

DO_INSTALL=1    # 0 = --no-install
DO_SYSTEMD=1    # 0 = --no-systemd
DRY_RUN=0

usage() {
  cat <<'EOF'
Usage:
  ./install.sh                  # npm i -g if paseo is missing; sniff the login shell;
                                # write ~/.config/environment.d/60-paseo.conf;
                                # generate and enable paseo.service
  ./install.sh --no-install     # skip npm install (paseo must already be on PATH)
  ./install.sh --no-systemd     # no unit, no sniffing: only npm i -g + `paseo daemon start`
                                #   (detached; inherits this terminal; no boot autostart)
  ./install.sh --dry-run        # sniff and print the unit / commands; write nothing
  ./install.sh -h | --help
EOF
  exit "${1:-0}"
}

step() { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m    %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m[warn] %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31m[error] %s\033[0m\n' "$*" >&2; exit 1; }

# command -v + readlink -f: resolve the real absolute path of a binary (nvm's
# bin entries are symlinks).
resolve_bin() {
  local p
  p="$(command -v "$1" 2>/dev/null || true)"
  if [[ -z "$p" ]]; then return 1; fi
  readlink -f "$p" 2>/dev/null || realpath "$p" 2>/dev/null || printf '%s\n' "$p"
}

# Non-interactive environments often lack npm on PATH (nvm); fall back to
# sourcing nvm when node/npm are missing.
ensure_nvm() {
  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    return 0
  fi
  local nvm_sh="${NVM_DIR:-$HOME/.nvm}/nvm.sh"
  if [[ -s "$nvm_sh" ]]; then
    # shellcheck disable=SC1090
    . "$nvm_sh"
  fi
  command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1
}

# Read the PID from ~/.paseo/paseo.pid (written by the daemon; empty output when unset).
daemon_pid() {
  [[ -f "$PID_FILE" ]] || return 0
  python3 - "$PID_FILE" <<'PY' || true
import json, sys
try:
    pid = json.load(open(sys.argv[1])).get("pid")
    print(pid if isinstance(pid, int) and pid > 0 else "")
except Exception:
    pass
PY
}

port_open() {
  timeout 1 bash -c "exec 3<>/dev/tcp/$LISTEN_ADDR/$LISTEN_PORT" 2>/dev/null
}

wait_port_open() {  # $1 = max seconds to wait
  local i
  for ((i = 0; i < $1; i++)); do
    if port_open; then return 0; fi
    sleep 1
  done
  return 1
}

wait_port_closed() {  # $1 = max seconds to wait
  local i
  for ((i = 0; i < $1; i++)); do
    if ! port_open; then return 0; fi
    sleep 1
  done
  return 1
}

# The unit body is expanded at call time; the global PASEO_BIN must be set.
# PATH is not written into the unit: Environment= replaces the whole variable
# and does not expand $PATH. The login-shell environment is written to
# ~/.config/environment.d/60-paseo.conf by sync_login_env.py; after
# daemon-reload the user manager hands it to user services started afterwards.
# daemon-reload alone does NOT refresh variables the manager already holds
# (PATH is pinned when the user manager starts, long before this file exists),
# so systemd_install also pushes the probed PATH via set-environment.
# `paseo daemon run` keeps the daemon in the foreground (CLI >= 0.9.2; the old
# `--foreground` flag of `daemon start` was removed).
unit_body() {
  cat <<EOF
[Unit]
Description=Paseo daemon (user service, generated by deploy/paseo-daemon/install.sh)
After=default.target

[Service]
Type=simple
# Generated by install.sh — do not hand-edit ExecStart; re-run the installer.
# Login-shell environment: ~/.config/environment.d/60-paseo.conf
ExecStart=$PASEO_BIN daemon run --home $PASEO_HOME
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
}

sync_login_env() {
  local -a args=()
  if [[ "$DRY_RUN" -eq 1 ]]; then
    args+=(--dry-run)
  fi
  python3 "$SCRIPT_DIR/sync_login_env.py" "${args[@]}"
}

show_status() {
  "$PASEO_BIN" daemon status --no-color 2>&1 || true
  echo
  systemctl --user status "$UNIT_NAME" --no-pager 2>&1 | sed -n '1,8p' || true
}

install_cli() {
  step "Install @getpaseo/cli: npm install -g @getpaseo/cli"
  npm install -g @getpaseo/cli
  ok "installed: $(command -v paseo)"
}

start_detached() {
  local pid
  pid="$(daemon_pid)"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    warn "daemon already running (PID $pid); skipping start"
  else
    step "paseo daemon start (detached)"
    "$PASEO_BIN" daemon start
  fi
  sleep 1
  show_status
  warn "detached mode has no boot autostart: re-run this script (without --no-systemd) after a reboot."
}

run_systemctl() {
  systemctl --user "$@" 2>&1 \
    || die "systemctl --user failed ($*): run this script from a real login session (a normal SSH/desktop terminal, not an environment without a user bus)."
}

# daemon-reload re-runs the environment generators but does not override
# variables the user manager already holds; PATH in practice is pinned when
# the user manager starts (at boot/login), long before 60-paseo.conf exists.
# Push the freshly probed PATH into the manager so this and later services
# actually get it. Non-fatal: without it services keep the stale manager PATH.
push_manager_path() {
  step "Refreshing the user manager PATH from the login shell"
  local probed
  if ! probed="$(python3 "$SCRIPT_DIR/sync_login_env.py" --emit-env PATH 2>/dev/null)"; then
    warn "login-shell PATH probe failed; leaving the user manager PATH untouched"
    return 0
  fi
  if [[ -z "$probed" ]]; then
    warn "login-shell PATH probe returned empty; leaving the user manager PATH untouched"
    return 0
  fi
  if systemctl --user set-environment "PATH=$probed" 2>/dev/null; then
    ok "user manager PATH refreshed"
  else
    warn "systemctl --user set-environment PATH failed; services may keep a stale PATH"
  fi
}

systemd_install() {
  step "Generate $UNIT_PATH"
  mkdir -p "$UNIT_DIR"
  printf '%s\n' "$(unit_body)" >"$UNIT_PATH"
  ok "unit written"

  step "systemctl --user daemon-reload"
  run_systemctl daemon-reload
  push_manager_path

  if systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null; then
    step "paseo.service is active -> restart"
    run_systemctl restart "$UNIT_NAME"
  else
    local pid
    pid="$(daemon_pid)"
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      warn "found an old unmanaged daemon (PID $pid); stopping it so it cannot hold $LISTEN_ADDR:$LISTEN_PORT"
      "$PASEO_BIN" daemon stop || true
      wait_port_closed 10 \
        || warn "old daemon may still be listening; if the new instance fails to start, see the tail of $LOG_FILE"
    fi
    step "systemctl --user enable --now $UNIT_NAME"
    run_systemctl enable --now "$UNIT_NAME"
  fi
}

enable_linger() {
  step "loginctl enable-linger \"$USER\" (start at boot even when not logged in)"
  if loginctl enable-linger "$USER" 2>/dev/null; then
    ok "linger: $(loginctl show-user "$USER" -p Linger 2>/dev/null | cut -d= -f2)"
  else
    warn "enable-linger failed; run this in a session with sudo: sudo loginctl enable-linger \"$USER\""
  fi
}

verify() {
  step "Waiting for the daemon to become ready ($LISTEN_ADDR:$LISTEN_PORT)"
  local ready=0
  if wait_port_open 30; then
    ready=1
  elif systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null \
    && "$PASEO_BIN" daemon status --no-color 2>/dev/null | grep -qiE 'localDaemon:[[:space:]]*running'; then
    ready=1
  fi
  if [[ "$ready" -eq 0 ]]; then
    warn "port probe failed; diagnostics:"
    show_status || true
    tail -n 30 "$LOG_FILE" 2>/dev/null || true
    journalctl --user -u "$UNIT_NAME" -n 30 --no-pager 2>/dev/null || true
    die "daemon is not ready; see the logs above"
  fi
  ok "daemon is ready"
  show_status
}

print_cheatsheet() {
  cat <<EOF

Installed. Common commands:
  paseo daemon status                         # the daemon's own view
  systemctl --user status $UNIT_NAME          # systemd's view
  systemctl --user restart $UNIT_NAME         # restart manually
  journalctl --user -u $UNIT_NAME -f          # systemd journal
  tail -f $LOG_FILE                            # daemon log
  # Login-shell snapshot: ~/.config/environment.d/60-paseo.conf
  # Re-run this script after changing ~/.bashrc / ~/.bash_profile, then restart paseo.service

The GUI/SSH transport only connects to a daemon that is already running; it does
not install or start one. As long as the local daemon runs, remote connects work.
Relay/QR pairing is a separate thing: paseo daemon pair.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-install) DO_INSTALL=0; shift ;;
    --no-systemd) DO_SYSTEMD=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "unknown option: $1" >&2; usage 1 ;;
  esac
done

# ---- dry-run: print only; write nothing, start nothing ----
if [[ "$DRY_RUN" -eq 1 ]]; then
  if [[ "$DO_SYSTEMD" -eq 1 ]]; then
    sync_login_env
  else
    echo "skipping login-shell sniff (--no-systemd inherits this terminal)"
  fi
  PASEO_BIN="$(resolve_bin paseo 2>/dev/null || true)"
  if [[ -z "$PASEO_BIN" ]]; then
    echo "planned: npm install -g @getpaseo/cli"
    echo "(run --dry-run again once paseo is installed to preview the unit)"
    exit 0
  fi
  echo "paseo (real): $PASEO_BIN"
  if [[ "$DO_SYSTEMD" -eq 1 ]]; then
    echo "unit path : $UNIT_PATH"
    echo "---- unit ----"
    unit_body
    echo "---- planned commands ----"
    echo "systemctl --user daemon-reload"
    probed_path="$(python3 "$SCRIPT_DIR/sync_login_env.py" --emit-env PATH 2>/dev/null)" || probed_path=""
    if [[ -n "$probed_path" ]]; then
      echo "systemctl --user set-environment PATH=$probed_path"
    else
      echo "systemctl --user set-environment PATH=<probe failed; will be skipped at runtime>"
    fi
    echo "systemctl --user enable --now $UNIT_NAME"
    echo "loginctl enable-linger \"$USER\""
  else
    echo "planned: $PASEO_BIN daemon start && $PASEO_BIN daemon status"
  fi
  exit 0
fi

# ---- real flow ----
ensure_nvm || die "node/npm not on PATH (this script tried sourcing \$NVM_DIR/nvm.sh). First: source ~/.nvm/nvm.sh"

if resolve_bin paseo >/dev/null 2>&1; then
  step "paseo already installed: $(command -v paseo)"
elif [[ "$DO_INSTALL" -eq 0 ]]; then
  die "--no-install given but paseo is not on PATH"
else
  install_cli
fi

PASEO_BIN="$(resolve_bin paseo)" || die "cannot find the paseo executable"

if [[ "$DO_SYSTEMD" -eq 1 ]]; then
  step "Sniffing the login shell; writing environment.d"
  sync_login_env
  systemd_install
  enable_linger
  verify
else
  start_detached
fi

print_cheatsheet
