#!/usr/bin/env bash
# Paseo daemon 一键部署: 安装 CLI → systemd --user 常驻(开机自启) → 校验。
#
# 背景: Paseo GUI 的 Remote/SSH 只连"已经在跑"的 daemon, 不会在远端安装、启动或
# 配置它; `paseo daemon start` 也只是 detach 一个后台进程(写 ~/.paseo/paseo.pid、
# daemon.log), 不注册开机自启 —— 机器一重启 6767 又没人听了。
# 本脚本参考 deploy/systemd/install-user-daemon.sh 的思路: 把 daemon 交给
# systemd --user + loginctl enable-linger 托管, 崩溃/重启后自动拉起。
#
# 用法:
#   ./install.sh                  # 缺 paseo 则 npm i -g; 生成并启用 paseo.service
#   ./install.sh --no-install     # 跳过 npm install(要求 paseo 已在 PATH)
#   ./install.sh --no-systemd     # 不写 unit: 只 npm i -g + paseo daemon start
#                                 #   (后台进程, 不跨重启)
#   ./install.sh --dry-run        # 打印将生成的 unit / 将执行的命令, 不落盘
#   ./install.sh -h | --help
#
# 环境变量: PASEO_HOME(默认 ~/.paseo)、PASEO_LISTEN_ADDR(默认 127.0.0.1)、
#           PASEO_PORT(默认 6767) 可覆盖就绪探测目标。

set -euo pipefail

UNIT_NAME="paseo.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"
PASEO_HOME="${PASEO_HOME:-$HOME/.paseo}"
PID_FILE="$PASEO_HOME/paseo.pid"
LOG_FILE="$PASEO_HOME/daemon.log"
LISTEN_ADDR="${PASEO_LISTEN_ADDR:-127.0.0.1}"
LISTEN_PORT="${PASEO_PORT:-6767}"

DO_INSTALL=1    # 0 = --no-install
DO_SYSTEMD=1    # 0 = --no-systemd
DRY_RUN=0

usage() {
  sed -n '2,19p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

step() { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m    %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m[警告] %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31m[错误] %s\033[0m\n' "$*" >&2; exit 1; }

# command -v + readlink -f: 拿到可执行文件的真实绝对路径(nvm 的 bin 是软链)。
resolve_bin() {
  local p
  p="$(command -v "$1" 2>/dev/null || true)"
  if [[ -z "$p" ]]; then return 1; fi
  readlink -f "$p" 2>/dev/null || realpath "$p" 2>/dev/null || printf '%s\n' "$p"
}

# 非交互环境(npm 常被 nvm 挡在 PATH 外): 找不到 node/npm 时尝试 source nvm。
ensure_nvm() {
  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then
    return 0
  fi
  local nvm_sh="${NVM_DIR:-$HOME/.nvm}/nvm.sh"
  if [[ -s "$nvm_sh" ]]; then
    # shellcheck disable=SC1090
    . "$nvm_sh"
  fi
  command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1
}

# 读 ~/.paseo/paseo.pid 里的 PID(daemon 自己写; 空则返回空串)。
daemon_pid() {
  [[ -f "$PID_FILE" ]] || return 0
  python3 - "$PID_FILE" <<'PY' || true
import json, sys
try:
    pid = json.load(open(sys.argv[1])).get("pid")
    print(pid if isinstance(pid, int) and pid > 0 else "")
except Exception:
    pass
PY
}

port_open() {
  timeout 1 bash -c "exec 3<>/dev/tcp/$LISTEN_ADDR/$LISTEN_PORT" 2>/dev/null
}

wait_port_open() {  # $1 = 最多等几秒
  local i
  for ((i = 0; i < $1; i++)); do
    if port_open; then return 0; fi
    sleep 1
  done
  return 1
}

wait_port_closed() {  # $1 = 最多等几秒
  local i
  for ((i = 0; i < $1; i++)); do
    if ! port_open; then return 0; fi
    sleep 1
  done
  return 1
}

# unit 内容在调用时才展开, 依赖全局 PASEO_BIN / ENV_PATH 已赋值。
unit_body() {
  cat <<EOF
[Unit]
Description=Paseo daemon (user service, generated by deploy/paseo-daemon/install.sh)
After=default.target

[Service]
Type=simple
# Generated by install.sh — do not hand-edit ExecStart/PATH; re-run the installer.
ExecStart=$PASEO_BIN daemon start --foreground
Restart=on-failure
RestartSec=5
Environment=PATH=$ENV_PATH

[Install]
WantedBy=default.target
EOF
}

show_status() {
  "$PASEO_BIN" daemon status --no-color 2>&1 || true
  echo
  systemctl --user status "$UNIT_NAME" --no-pager 2>&1 | sed -n '1,8p' || true
}

install_cli() {
  step "安装 @getpaseo/cli: npm install -g @getpaseo/cli"
  npm install -g @getpaseo/cli
  ok "已安装: $(command -v paseo)"
}

start_detached() {
  local pid
  pid="$(daemon_pid)"
  if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
    warn "daemon 已在运行(PID $pid), 跳过 start"
  else
    step "paseo daemon start (detached)"
    "$PASEO_BIN" daemon start
  fi
  sleep 1
  show_status
  warn "detached 模式不注册开机自启: 重启后需重跑本脚本(不带 --no-systemd)。"
}

run_systemctl() {
  systemctl --user "$@" 2>&1 \
    || die "systemctl --user 失败($*): 请从真实登录会话运行本脚本(普通 SSH/桌面终端, 而非无 user bus 的环境)。"
}

systemd_install() {
  step "生成 $UNIT_PATH"
  mkdir -p "$UNIT_DIR"
  printf '%s\n' "$(unit_body)" >"$UNIT_PATH"
  ok "unit 已写入"

  step "systemctl --user daemon-reload"
  run_systemctl daemon-reload

  if systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null; then
    step "paseo.service 已激活 → restart"
    run_systemctl restart "$UNIT_NAME"
  else
    local pid
    pid="$(daemon_pid)"
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      warn "存在旧的非托管 daemon(PID $pid), 先停掉, 避免占用 $LISTEN_ADDR:$LISTEN_PORT"
      "$PASEO_BIN" daemon stop || true
      wait_port_closed 10 \
        || warn "旧 daemon 可能还在监听; 若新实例起不来, 看 $LOG_FILE 尾部"
    fi
    step "systemctl --user enable --now $UNIT_NAME"
    run_systemctl enable --now "$UNIT_NAME"
  fi
}

enable_linger() {
  step "loginctl enable-linger \"$USER\" (未登录也随开机自启)"
  if loginctl enable-linger "$USER" 2>/dev/null; then
    ok "linger: $(loginctl show-user "$USER" -p Linger 2>/dev/null | cut -d= -f2)"
  else
    warn "enable-linger 失败: 可在有 sudo 的会话执行: sudo loginctl enable-linger \"$USER\""
  fi
}

verify() {
  step "等待 daemon 就绪 ($LISTEN_ADDR:$LISTEN_PORT)"
  local ready=0
  if wait_port_open 30; then
    ready=1
  elif systemctl --user is-active --quiet "$UNIT_NAME" 2>/dev/null \
    && "$PASEO_BIN" daemon status --no-color 2>/dev/null | grep -qiE 'local daemon.*running'; then
    ready=1
  fi
  if [[ "$ready" -eq 0 ]]; then
    warn "端口探测失败, 打印诊断:"
    show_status || true
    tail -n 30 "$LOG_FILE" 2>/dev/null || true
    journalctl --user -u "$UNIT_NAME" -n 30 --no-pager 2>/dev/null || true
    die "daemon 未就绪, 见上方日志"
  fi
  ok "daemon 已就绪"
  show_status
}

print_cheatsheet() {
  cat <<EOF

安装完成。常用命令:
  paseo daemon status                         # daemon 自身视角
  systemctl --user status $UNIT_NAME          # systemd 视角
  systemctl --user restart $UNIT_NAME         # 手动重启
  journalctl --user -u $UNIT_NAME -f          # systemd 日志
  tail -f $LOG_FILE                            # daemon 日志

GUI/SSH 只连"已经在跑"的 daemon, 不负责安装/启动; 只要本机 daemon 在跑, 远端就能连。
relay/扫码配对是另一回事: paseo daemon pair。
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-install) DO_INSTALL=0; shift ;;
    --no-systemd) DO_SYSTEMD=0; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "未知选项: $1" >&2; usage 1 ;;
  esac
done

# ---- dry-run: 只打印, 不落盘/不启动 ----
if [[ "$DRY_RUN" -eq 1 ]]; then
  PASEO_BIN="$(resolve_bin paseo 2>/dev/null || true)"
  if [[ -z "$PASEO_BIN" ]]; then
    echo "计划执行: npm install -g @getpaseo/cli"
    echo "(paseo 装好后再次 --dry-run 可预览 unit 内容)"
    exit 0
  fi
  NODE_BIN="$(resolve_bin node)"
  ENV_PATH="$(dirname "$NODE_BIN"):$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin"
  echo "paseo (real): $PASEO_BIN"
  echo "node dir    : $(dirname "$NODE_BIN")"
  if [[ "$DO_SYSTEMD" -eq 1 ]]; then
    echo "unit 路径    : $UNIT_PATH"
    echo "---- unit ----"
    unit_body
    echo "---- 将执行 ----"
    echo "systemctl --user daemon-reload"
    echo "systemctl --user enable --now $UNIT_NAME"
    echo "loginctl enable-linger \"$USER\""
  else
    echo "将执行: $PASEO_BIN daemon start && $PASEO_BIN daemon status"
  fi
  exit 0
fi

# ---- 正式流程 ----
ensure_nvm || die "node/npm 不在 PATH(本脚本尝试过 source \$NVM_DIR/nvm.sh)。请先: source ~/.nvm/nvm.sh"

if resolve_bin paseo >/dev/null 2>&1; then
  step "paseo 已安装: $(command -v paseo)"
elif [[ "$DO_INSTALL" -eq 0 ]]; then
  die "--no-install 但 paseo 不在 PATH"
else
  install_cli
fi

PASEO_BIN="$(resolve_bin paseo)" || die "找不到 paseo 可执行文件"
NODE_BIN="$(resolve_bin node)"
ENV_PATH="$(dirname "$NODE_BIN"):$HOME/.local/bin:$HOME/bin:/usr/local/bin:/usr/bin:/bin"

if [[ "$DO_SYSTEMD" -eq 1 ]]; then
  systemd_install
  enable_linger
  verify
else
  start_detached
fi

print_cheatsheet
