#!/usr/bin/env python3
"""Write a login-shell environment snapshot to the user environment.d directory.

systemd user services do not read shell startup files. This probe runs the
login shell once, with a clean environment, and writes the resulting
assignments to ``60-paseo.conf``. The unit no longer sets ``PATH``, so later
``systemctl --user daemon-reload`` exports this snapshot to services started
afterwards, including paseo.
"""

from __future__ import annotations

import argparse
import os
import pwd
import shutil
import subprocess
import sys
from collections.abc import Callable, Mapping, Sequence
from pathlib import Path

ENV_FILE_NAME = "60-paseo.conf"
PROBE_TIMEOUT_SEC = 60

# Session and shell bookkeeping. Persisting these would pin a graphical or SSH
# session onto every future user service, including ones started at boot.
EXCLUDED_KEYS = frozenset(
    {
        "_",
        "SHLVL",
        "PWD",
        "OLDPWD",
        "SHELLOPTS",
        "BASHOPTS",
        "DISPLAY",
        "WAYLAND_DISPLAY",
        "WAYLAND_SOCKET",
        "XAUTHORITY",
        "DBUS_SESSION_BUS_ADDRESS",
        "DBUS_SESSION_BUS_PID",
        "XDG_RUNTIME_DIR",
        "SSH_AUTH_SOCK",
        "SSH_AGENT_PID",
        "SSH_CONNECTION",
        "SSH_CLIENT",
        "SSH_TTY",
        "PULSE_SERVER",
        "PULSE_RUNTIME_PATH",
        "XDG_SESSION_ID",
        "XDG_SESSION_TYPE",
        "XDG_SESSION_CLASS",
        "XDG_SESSION_DESKTOP",
        "XDG_SEAT",
        "XDG_VTNR",
        "GPG_AGENT_INFO",
    }
)

Runner = Callable[[Sequence[str], float], subprocess.CompletedProcess[bytes]]


class ProbeError(RuntimeError):
    pass


def default_runner(argv: Sequence[str], timeout: float) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(argv, capture_output=True, timeout=timeout, check=False)


def parse_env0(blob: bytes) -> dict[str, str]:
    parsed: dict[str, str] = {}
    for item in blob.split(b"\0"):
        if not item or b"=" not in item:
            continue
        raw_key, raw_value = item.split(b"=", 1)
        try:
            key = raw_key.decode("utf-8")
            value = raw_value.decode("utf-8")
        except UnicodeDecodeError:
            continue
        parsed[key] = value
    return parsed


def valid_key(key: str) -> bool:
    if not key or key in EXCLUDED_KEYS or key.startswith("BASH_FUNC_"):
        return False
    first = key[0]
    if not (first.isascii() and (first.isalpha() or first == "_")):
        return False
    return all(char.isascii() and (char.isalnum() or char == "_") for char in key[1:])


def escape_env_value(value: str) -> str:
    # environment.d expands $VAR and treats \X as escaped X. $$ is one dollar
    # and \\ is one backslash. A single trailing backslash would continue the line.
    return value.replace("\\", "\\\\").replace("$", "$$")


def assignment_line(key: str, value: str) -> str | None:
    if "\n" in value or "\x00" in value:
        return None
    return f"{key}={escape_env_value(value)}"


def select_env(env: Mapping[str, str]) -> dict[str, str]:
    selected: dict[str, str] = {}
    for key, value in env.items():
        if not valid_key(key) or assignment_line(key, value) is None:
            continue
        selected[key] = value
    return selected


def render(env: Mapping[str, str]) -> str:
    lines = [
        "# Generated by deploy/paseo-daemon/sync_login_env.py. Re-run install.sh to refresh.",
        "# Login-shell snapshot for systemd user services. systemd reads *.conf only.",
        "",
    ]
    for key in sorted(env):
        line = assignment_line(key, env[key])
        if line is not None:
            lines.append(line)
    lines.append("")
    return "\n".join(lines)


def default_dest() -> Path:
    xdg = os.environ.get("XDG_CONFIG_HOME")
    config = Path(xdg) if xdg else Path.home() / ".config"
    return config / "environment.d" / ENV_FILE_NAME


def write_env_file(dest: Path, content: str) -> Path | None:
    dest.parent.mkdir(parents=True, mode=0o700, exist_ok=True)
    backup: Path | None = None
    if dest.exists():
        backup = dest.with_name(dest.name + ".bak")
        shutil.copy2(dest, backup)
        os.chmod(backup, 0o600)
    temporary = dest.with_name(dest.name + ".tmp")
    try:
        temporary.write_text(content, encoding="utf-8")
        os.chmod(temporary, 0o600)
        os.replace(temporary, dest)
    finally:
        if temporary.exists():
            temporary.unlink()
    os.chmod(dest, 0o600)
    return backup


def path_has_executable(path_value: str, name: str) -> bool:
    for entry in path_value.split(":"):
        if entry and os.access(os.path.join(entry, name), os.X_OK):
            return True
    return False


def login_shell() -> str:
    shell = os.environ.get("SHELL", "").strip()
    if shell:
        return shell
    return pwd.getpwuid(os.getuid()).pw_shell or "/bin/bash"


def probe_login_env(
    *,
    shell: str,
    home: str,
    user: str,
    runner: Runner | None = None,
    timeout: float = PROBE_TIMEOUT_SEC,
) -> dict[str, str]:
    if runner is None:
        runner = default_runner
    argv = [
        "env",
        "-i",
        f"HOME={home}",
        f"USER={user}",
        f"LOGNAME={user}",
        f"SHELL={shell}",
        "PATH=/usr/bin:/bin",
        "TERM=dumb",
        shell,
        "--login",
        "-c",
        "env -0",
    ]
    try:
        completed = runner(argv, timeout)
    except subprocess.TimeoutExpired as error:
        raise ProbeError(
            f"login shell probe timed out after {timeout:.0f}s; {shell} startup files did not finish"
        ) from error
    if completed.returncode != 0:
        err = completed.stderr.decode("utf-8", errors="replace").strip()
        detail = err[-500:] if err else f"exit {completed.returncode}"
        raise ProbeError(f"login shell probe failed: {detail}")
    selected = select_env(parse_env0(completed.stdout))
    if not path_has_executable(selected.get("PATH", ""), "node"):
        raise ProbeError(
            "login shell PATH does not contain node. "
            "Paseo's shebang is /usr/bin/env node, so the user manager PATH must include it."
        )
    return selected


def sync(*, dest: Path, dry_run: bool) -> int:
    home = str(Path.home())
    user = os.environ.get("USER") or pwd.getpwuid(os.getuid()).pw_name
    shell = login_shell()
    env = probe_login_env(shell=shell, home=home, user=user)
    print(f"login shell: {shell}")
    print(f"variables: {len(env)}")
    print(f"environment.d: {dest}")
    if dry_run:
        print("dry-run: not written")
        print("keys: " + ", ".join(sorted(env)))
        return 0
    backup = write_env_file(dest, render(env))
    if backup is not None:
        print(f"backup: {backup}")
    else:
        print("backup: none (no previous file)")
    return 0


def emit_env(*, key: str) -> int:
    """Probe the login shell and print the raw value of one variable.

    Writes nothing. Used by install.sh to push the probed PATH into the
    user manager, because daemon-reload does not override variables the
    manager already holds.
    """
    home = str(Path.home())
    user = os.environ.get("USER") or pwd.getpwuid(os.getuid()).pw_name
    shell = login_shell()
    env = probe_login_env(shell=shell, home=home, user=user)
    if key not in env:
        print(f"error: {key} not found in the login-shell environment", file=sys.stderr)
        return 1
    print(env[key])
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dest",
        type=Path,
        default=None,
        help=f"output file (default: ~/.config/environment.d/{ENV_FILE_NAME})",
    )
    parser.add_argument("--dry-run", action="store_true", help="probe and print key names only")
    parser.add_argument(
        "--emit-env",
        metavar="NAME",
        default=None,
        help="probe and print the raw value of NAME (writes nothing)",
    )
    args = parser.parse_args(argv)
    if args.emit_env is not None:
        try:
            return emit_env(key=args.emit_env)
        except ProbeError as error:
            print(f"error: {error}", file=sys.stderr)
            return 1
    dest = args.dest if args.dest is not None else default_dest()
    try:
        return sync(dest=dest, dry_run=args.dry_run)
    except ProbeError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
