import contextlib
import io
import os
import stat
import subprocess
import tempfile
import unittest
from pathlib import Path

import sync_login_env as sync


class ParseAndSelectTest(unittest.TestCase):
    def test_parses_nul_assignments_and_drops_session_keys(self) -> None:
        blob = b"PATH=/usr/bin\0DISPLAY=:1\0SHLVL=1\0FOO=a=b\0BASH_FUNC_x%%=() { :; }\0"
        selected = sync.select_env(sync.parse_env0(blob))
        self.assertEqual(selected, {"PATH": "/usr/bin", "FOO": "a=b"})

    def test_skips_values_that_cannot_be_one_line(self) -> None:
        selected = sync.select_env({"OK": "fine", "BAD": "a\nb"})
        self.assertEqual(selected, {"OK": "fine"})


class EscapeTest(unittest.TestCase):
    def test_escapes_dollar_and_backslash_for_environment_d(self) -> None:
        self.assertEqual(sync.escape_env_value(r"a\b$c"), r"a\\b$$c")
        self.assertEqual(sync.assignment_line("END", "tail\\"), "END=tail\\\\")
        self.assertFalse(sync.assignment_line("END", "tail\\").endswith("\\\n"))


class WriteTest(unittest.TestCase):
    def test_backs_up_previous_file_and_keeps_mode_private(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            dest = Path(raw) / "environment.d" / "60-paseo.conf"
            dest.parent.mkdir()
            dest.write_text("OLD=1\n", encoding="utf-8")
            os.chmod(dest, 0o644)
            backup = sync.write_env_file(dest, sync.render({"PATH": "/bin", "Z": "x"}))
            self.assertEqual(backup, dest.with_name("60-paseo.conf.bak"))
            self.assertEqual(backup.read_text(encoding="utf-8"), "OLD=1\n")
            text = dest.read_text(encoding="utf-8")
            self.assertIn("PATH=/bin\n", text)
            self.assertIn("Z=x\n", text)
            self.assertTrue(text.startswith("# Generated by deploy/paseo-daemon/sync_login_env.py"))
            self.assertEqual(stat.S_IMODE(dest.stat().st_mode), 0o600)
            self.assertEqual(stat.S_IMODE(backup.stat().st_mode), 0o600)
            self.assertFalse((dest.with_name("60-paseo.conf.tmp")).exists())


class ProbeTest(unittest.TestCase):
    def test_requires_node_on_the_probed_path(self) -> None:
        def runner(argv: list[str], timeout: float) -> subprocess.CompletedProcess[bytes]:
            del argv, timeout
            return subprocess.CompletedProcess(
                args=[],
                returncode=0,
                stdout=b"PATH=/no/such/bin\0HOME=/home/user\0",
                stderr=b"",
            )

        with self.assertRaises(sync.ProbeError):
            sync.probe_login_env(shell="/bin/bash", home="/home/user", user="user", runner=runner)

    def test_accepts_a_path_that_contains_node(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            node = Path(raw) / "node"
            node.write_text("#!/bin/sh\n", encoding="utf-8")
            node.chmod(0o755)

            def runner(argv: list[str], timeout: float) -> subprocess.CompletedProcess[bytes]:
                del timeout
                self.assertIn("--login", argv)
                self.assertEqual(argv[0], "env")
                self.assertIn("PATH=/usr/bin:/bin", argv)
                stdout = f"PATH={raw}\0DISPLAY=:1\0NVM_DIR=/nvm\0".encode()
                return subprocess.CompletedProcess(args=[], returncode=0, stdout=stdout, stderr=b"")

            env = sync.probe_login_env(
                shell="/bin/bash",
                home="/home/user",
                user="user",
                runner=runner,
            )
            self.assertEqual(env["PATH"], raw)
            self.assertEqual(env["NVM_DIR"], "/nvm")
            self.assertNotIn("DISPLAY", env)


class EmitEnvTest(unittest.TestCase):
    def test_emit_env_prints_raw_value_and_writes_nothing(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            node = Path(raw) / "node"
            node.write_text("#!/bin/sh\n", encoding="utf-8")
            node.chmod(0o755)

            def runner(argv: list[str], timeout: float) -> subprocess.CompletedProcess[bytes]:
                del argv, timeout
                return subprocess.CompletedProcess(
                    args=[],
                    returncode=0,
                    stdout=f"PATH={raw}\0HOME=/h\0".encode(),
                    stderr=b"",
                )

            original = sync.default_runner
            sync.default_runner = runner
            try:
                dest = Path(raw) / "environment.d" / "60-paseo.conf"
                buf = io.StringIO()
                with contextlib.redirect_stdout(buf):
                    rc = sync.main(["--emit-env", "PATH", "--dest", str(dest)])
                self.assertEqual(rc, 0)
                self.assertEqual(buf.getvalue().strip(), raw)
                self.assertFalse(dest.exists())
            finally:
                sync.default_runner = original

    def test_emit_env_fails_when_key_is_missing(self) -> None:
        def runner(argv: list[str], timeout: float) -> subprocess.CompletedProcess[bytes]:
            del argv, timeout
            return subprocess.CompletedProcess(args=[], returncode=0, stdout=b"HOME=/h\0", stderr=b"")

        original = sync.default_runner
        sync.default_runner = runner
        try:
            with tempfile.TemporaryDirectory() as raw:
                dest = Path(raw) / "environment.d" / "60-paseo.conf"
                buf = io.StringIO()
                with contextlib.redirect_stdout(buf):
                    rc = sync.main(["--emit-env", "PATH", "--dest", str(dest)])
                self.assertEqual(rc, 1)
                self.assertEqual(buf.getvalue(), "")
        finally:
            sync.default_runner = original


if __name__ == "__main__":
    unittest.main()
