#!/usr/bin/env bash
# Install MaintainAll as a systemd --user unit using the *current* interpreter.
#
# Works with conda, venv, uv, or system Python: run this script from the same
# environment you use for `pip install -e .` / `maintainall`.
#
# Usage:
#   ./deploy/systemd/install-user-daemon.sh
#   ./deploy/systemd/install-user-daemon.sh --python /path/to/python
#   ./deploy/systemd/install-user-daemon.sh --dry-run

set -euo pipefail

UNIT_NAME="maintainall-agent.service"
UNIT_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
UNIT_PATH="$UNIT_DIR/$UNIT_NAME"
DRY_RUN=0
PYTHON_BIN=""

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --python)
      PYTHON_BIN="${2:?}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage 1
      ;;
  esac
done

if [[ -z "$PYTHON_BIN" ]]; then
  PYTHON_BIN="$(command -v python3 || command -v python || true)"
fi
if [[ -z "$PYTHON_BIN" || ! -x "$PYTHON_BIN" ]]; then
  echo "error: no usable python on PATH (activate conda/venv first, or pass --python)" >&2
  exit 1
fi
PYTHON_BIN="$(readlink -f "$PYTHON_BIN" 2>/dev/null || realpath "$PYTHON_BIN" 2>/dev/null || echo "$PYTHON_BIN")"

# Prefer console_script in the same env; fall back to python -m.
DAEMON_BIN="$(command -v maintainall-daemon || true)"
if [[ -n "$DAEMON_BIN" ]]; then
  DAEMON_BIN="$(readlink -f "$DAEMON_BIN" 2>/dev/null || realpath "$DAEMON_BIN" 2>/dev/null || echo "$DAEMON_BIN")"
  # Ensure the script's shebang env matches this python's bindir when possible.
  EXEC_START="$DAEMON_BIN"
  EXEC_DESC="maintainall-daemon at $DAEMON_BIN"
else
  if ! "$PYTHON_BIN" -c "import MaintainAll.daemon.service" 2>/dev/null; then
    echo "error: MaintainAll not importable with $PYTHON_BIN" >&2
    echo "  pip install -e .   # inside this conda/venv, then re-run" >&2
    exit 1
  fi
  EXEC_START="$PYTHON_BIN -m MaintainAll.daemon.service"
  EXEC_DESC="python -m MaintainAll.daemon.service via $PYTHON_BIN"
fi

BIN_DIR="$(dirname "$PYTHON_BIN")"
# Minimal PATH so child tools (systemctl probes are N/A; missions may call host cmds).
ENV_PATH="$BIN_DIR:/usr/bin:/bin"

UNIT_BODY=$(cat <<EOF
[Unit]
Description=MaintainAll AIOps mission daemon
After=default.target

[Service]
Type=simple
# Generated by deploy/systemd/install-user-daemon.sh — do not hand-edit ExecStart;
# re-run the installer after switching conda/venv.
ExecStart=$EXEC_START
Restart=on-failure
RestartSec=5
# Ensure the env that owns MaintainAll is first on PATH (conda/venv bin).
Environment=PATH=$ENV_PATH

[Install]
WantedBy=default.target
EOF
)

echo "Python:     $PYTHON_BIN"
echo "ExecStart:  $EXEC_START ($EXEC_DESC)"
echo "Unit file:  $UNIT_PATH"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "---- dry-run unit ----"
  printf '%s\n' "$UNIT_BODY"
  exit 0
fi

mkdir -p "$UNIT_DIR"
printf '%s\n' "$UNIT_BODY" >"$UNIT_PATH"

systemctl --user daemon-reload
systemctl --user enable --now "$UNIT_NAME"
systemctl --user status "$UNIT_NAME" --no-pager || true

echo
echo "Installed. Useful commands:"
echo "  systemctl --user status $UNIT_NAME"
echo "  systemctl --user restart $UNIT_NAME"
echo "  journalctl --user -u $UNIT_NAME -f"
echo "Optional (run without login session): loginctl enable-linger \"\$USER\""
echo "After changing conda/venv: re-run this script from the new environment."
