import { describe, test, expect, beforeEach } from '@jest/globals';
import '../__mocks__/chrome.js';

let mergeKnowledgeBases, parseSections;

beforeAll(async () => {
  const mod = await import('../../lib/knowledge_base.js');
  ({ mergeKnowledgeBases, parseSections } = mod);
});

describe('parseSections', () => {
  test('parses markdown into sections by ## headings', () => {
    const md = `# Title
preamble text

## Section 1
content 1

## Section 2
content 2`;
    const sections = parseSections(md);
    expect(sections.size).toBe(2);
    expect(sections.get('Section 1')).toContain('## Section 1');
    expect(sections.get('Section 1')).toContain('content 1');
    expect(sections.get('Section 2')).toContain('content 2');
  });

  test('returns empty map for empty markdown', () => {
    expect(parseSections('').size).toBe(0);
    expect(parseSections(null).size).toBe(0);
  });

  test('returns empty map for single heading', () => {
    const sections = parseSections('# Just a title');
    expect(sections.size).toBe(0);
  });
});

describe('mergeKnowledgeBases', () => {
  test('returns local when no remote', () => {
    const local = `# KB
## Topic A
local content`;
    const { merged, stats } = mergeKnowledgeBases(local, '');
    expect(merged).toContain('Topic A');
    expect(stats.addedFromRemote).toBe(0);
  });

  test('returns remote when no local', () => {
    const remote = `# KB
## Topic B
remote content`;
    const { merged, stats } = mergeKnowledgeBases('', remote);
    expect(merged).toContain('Topic B');
    expect(stats.addedFromRemote).toBe(0);
  });

  test('merges remote-only sections into local', () => {
    const local = `# KB
## Topic A
local only`;
    const remote = `# KB
## Topic A
remote version
## Topic B
remote only`;
    const { merged, stats } = mergeKnowledgeBases(local, remote);
    // Topic A: local wins (local content preserved)
    expect(merged).toContain('local only');
    // Topic B: added from remote
    expect(merged).toContain('Topic B');
    expect(stats.addedFromRemote).toBe(1);
  });

  test('local wins on conflict with same section heading', () => {
    const local = `## Shared
local version`;
    const remote = `## Shared
remote version`;
    const { merged, stats } = mergeKnowledgeBases(local, remote);
    expect(merged).toContain('local version');
    expect(merged).not.toContain('remote version');
    expect(stats.addedFromRemote).toBe(0);
  });

  test('preserves preamble (text before first ##)', () => {
    const local = `# Knowledge Base
> generated by plugin

## Section
content`;
    const remote = `# Different KB
> different preamble

## Section
remote

## New
new content`;
    const { merged } = mergeKnowledgeBases(local, remote);
    // Local preamble wins
    expect(merged).toContain('# Knowledge Base');
    expect(merged).toContain('generated by plugin');
    // New remote section added
    expect(merged).toContain('new content');
  });

  test('handles identical markdown gracefully', () => {
    const md = `## Section
content`;
    const { merged, stats } = mergeKnowledgeBases(md, md);
    expect(merged).toBe(md);
    expect(stats.addedFromRemote).toBe(0);
  });
});
