[management]
mgmt01 ansible_host=intern04-02

[login]
login01 ansible_host=intern04-01

[compute]
compute01 ansible_host=intern04-03
compute02 ansible_host=intern04-04

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa