tproxy_port: "12345"
tproxy_port_protect: "true"
log_level: "info"
tcp_check_url: "http://cp.cloudflare.com,1.1.1.1,2606:4700:4700::1111"
tcp_check_http_method: "HEAD"
udp_check_dns: "dns.google:53,8.8.8.8,2001:4860:4860::8888"
check_interval: "30s"
check_tolerance: "50ms"
lan_interface: "wlp3s0"
wan_interface: "auto"
dial_mode: "domain"
allow_insecure: "false"
auto_config_kernel_parameter: "true"
sniffing_timeout: "100ms"
tls_implementation: "tls"
utls_imitate: "chrome_auto"
enable_local_tcp_fast_redirect: "true"
fallback_resolver: "8.8.8.8:53"
bandwidth_max_tx: "200 mbps"
bandwidth_max_rx: "1 gbps"