# addr2line2src $(addr2line -e xxx xxx)
# convert addr2line output to source code
function addr2line2src() {
    result=$1
    filename=$(echo $1 | cut -d':' -f1)
    line=$(echo $1 | cut -d':' -f2)
    sed -n "${line}p" "${filename}"
}

# rust mirror

function unset_rustup_mirror() {
    unset RUSTUP_UPDATE_ROOT
    unset RUSTUP_DIST_SERVER
}

function set_rustup_mirror() {
    export RUSTUP_UPDATE_ROOT=https://mirrors.cernet.edu.cn/rustup/rustup
    export RUSTUP_DIST_SERVER=https://mirrors.cernet.edu.cn/rustup
}

. set_rustup_mirror

# use ccache to speed up compilation

export CMAKE_CXX_COMPILER_LAUNCHER=ccache

# environment module common paths
. /usr/share/modules/init/bash
export MODULEPATH=${HOME}/envs:${HOME}/modulefiles:/opt/modulefiles:$MODULEPATH

function do_sync() {
sudo bash -c "echo 3 > /proc/sys/vm/drop_caches"
sudo sync
}

function loop_cmd_until_success() {
    exe_cmd=$1
    max_loops=${2:-'5'}
    eval $exe_cmd
    for i in `seq 1 $max_loops`; do
        eval $exe_cmd
        if [[ $? == 0 ]]; then
            break
        fi
    done
}

# Spack
# . ${HOME}/softwares/spack/share/spack/setup-env.sh
# spack load tmux
# spack load environment-modules

# For intel oneapi
# . /opt/intel/oneapi/setvars.sh

alias ssh-keygen-ed25519="ssh-keygen -t ed25519 -C \"you@email.domain\""
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias dkps='docker ps --all'
alias dkimgs='docker image ls --all'
