#!/usr/bin/env python3
"""AstrBot — minimal deployment helper.

Deploy only. This script brings the container up, takes it down, and
reports on it. It never writes AstrBot's configuration: no provider
injection, no plugin schema patching, no cmd_config.json edits. All
runtime configuration belongs to the operator and the WebUI.

Commands:
    setup-env   Generate .env (dashboard password, tag, naming)
    up          Pull the image and start the container
    down        Stop and remove the container (volumes kept)
    status      Read-only health check and configuration summary
    logs        Tail container logs
    shell       Open a shell inside the container
"""

from __future__ import annotations

import json
import secrets
import string
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

import click

SCRIPT_DIR = Path(__file__).resolve().parent
COMPOSE_FILE = SCRIPT_DIR / "docker-compose.yml"
ENV_PATH = SCRIPT_DIR / ".env"

CONFIG_IN_CONTAINER = "/AstrBot/data/cmd_config.json"

RED = "red"
GREEN = "green"
YELLOW = "yellow"
CYAN = "cyan"


# ---------------------------------------------------------------------------
# .env
# ---------------------------------------------------------------------------


def read_env() -> dict:
    """Parse .env into a dict. Missing file yields an empty dict."""
    data: dict[str, str] = {}
    if not ENV_PATH.exists():
        return data
    for raw in ENV_PATH.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        data[key.strip()] = value.strip()
    return data


def write_env(data: dict) -> None:
    lines = [
        "# ============================================================",
        "# AstrBot — minimal deployment environment",
        "# Generated by deploy.py setup-env.",
        "# ============================================================",
        "",
        "# --- Required ---",
        f"ASTRBOT_DASHBOARD_PASSWORD={data.get('ASTRBOT_DASHBOARD_PASSWORD', '')}",
        "",
        "# --- Optional: image / update control ---",
        f"ASTRBOT_TAG={data.get('ASTRBOT_TAG', 'latest')}",
        "",
        "# --- Optional: naming ---",
        f"ASTRBOT_CONTAINER={data.get('ASTRBOT_CONTAINER', 'astrbot')}",
        f"ASTRBOT_PORT={data.get('ASTRBOT_PORT', '6185')}",
        f"ASTRBOT_VOLUME={data.get('ASTRBOT_VOLUME', 'astrbot_data')}",
        "",
        "# --- Optional: misc ---",
        f"TZ={data.get('TZ', 'Asia/Shanghai')}",
        "",
    ]
    ENV_PATH.write_text("\n".join(lines) + "\n")


def generate_password(length: int = 20) -> str:
    """Password satisfying AstrBot's complexity rule.

    AstrBot rejects dashboard passwords without an upper case letter, a
    lower case letter and a digit, so generate until all three appear.
    """
    alphabet = string.ascii_letters + string.digits
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(length))
        if (
            any(c.islower() for c in candidate)
            and any(c.isupper() for c in candidate)
            and any(c.isdigit() for c in candidate)
        ):
            return candidate


def password_problem(password: str) -> str | None:
    """Return a human-readable reason the password is invalid, else None."""
    if len(password) < 8:
        return "must be at least 8 characters"
    if not any(c.islower() for c in password):
        return "must contain a lower case letter"
    if not any(c.isupper() for c in password):
        return "must contain an upper case letter"
    if not any(c.isdigit() for c in password):
        return "must contain a digit"
    return None


def ensure_dashboard_password(env: dict) -> str | None:
    """Guarantee a valid dashboard password in .env; return a new one if made.

    AstrBot's ``_resolve_initial_dashboard_password()`` validates the env
    value whenever it has to generate the dashboard credentials, and its
    ``validate_dashboard_password()`` rejects an empty string outright.
    This compose always passes ``ASTRBOT_DASHBOARD_INITIAL_PASSWORD``, so
    a blank (or too weak) value in .env would crash the container on a
    fresh volume with a cryptic ValueError. Substituting a valid value
    before starting removes that failure mode entirely.

    On an already-initialised volume the value is ignored by AstrBot, so
    regenerating is harmless there too.
    """
    password = env.get("ASTRBOT_DASHBOARD_PASSWORD", "")
    problem = password_problem(password) if password else "is not set"
    if not problem:
        return None
    generated = generate_password()
    env["ASTRBOT_DASHBOARD_PASSWORD"] = generated
    write_env(env)
    return generated


# ---------------------------------------------------------------------------
# docker helpers
# ---------------------------------------------------------------------------


def _compose(*args: str, check: bool = False) -> subprocess.CompletedProcess:
    cmd = ["docker", "compose", "-f", str(COMPOSE_FILE), *args]
    return subprocess.run(cmd, cwd=str(SCRIPT_DIR), check=check)


def _compose_capture(*args: str) -> subprocess.CompletedProcess:
    cmd = ["docker", "compose", "-f", str(COMPOSE_FILE), *args]
    return subprocess.run(
        cmd, cwd=str(SCRIPT_DIR), capture_output=True, text=True
    )


def docker_available() -> bool:
    try:
        return subprocess.run(
            ["docker", "version"], capture_output=True, timeout=10
        ).returncode == 0
    except Exception:
        return False


def compose_available() -> bool:
    try:
        return subprocess.run(
            ["docker", "compose", "version"], capture_output=True, timeout=10
        ).returncode == 0
    except Exception:
        return False


def container_name(env: dict) -> str:
    return env.get("ASTRBOT_CONTAINER", "astrbot")


def container_running(name: str) -> bool:
    try:
        r = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", name],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return r.stdout.strip() == "true"
    except Exception:
        return False


def http_ok(port: str, path: str = "/", timeout: int = 5) -> bool:
    try:
        with urllib.request.urlopen(
            f"http://127.0.0.1:{port}{path}", timeout=timeout
        ) as resp:
            return resp.status == 200
    except urllib.error.HTTPError as e:
        # A redirect or auth challenge still proves the dashboard is up.
        return e.code in (200, 301, 302, 401, 403)
    except Exception:
        return False


def wait_for_dashboard(port: str, attempts: int = 20, interval: int = 5) -> bool:
    for _ in range(attempts):
        if http_ok(port):
            return True
        time.sleep(interval)
    return False


# ---------------------------------------------------------------------------
# read-only config inspection
# ---------------------------------------------------------------------------

# Executed inside the container with `python3 -c`. Opens the config for
# reading only and prints a JSON summary. Never writes.
_INSPECT_SCRIPT = r"""
import json, sys

path = sys.argv[1]

def mask(value):
    if not value:
        return "<empty>"
    text = str(value)
    return text[:6] + "..." if len(text) > 6 else "<set>"

try:
    with open(path, encoding="utf-8-sig") as fh:
        cfg = json.load(fh)
except FileNotFoundError:
    print(json.dumps({"error": "config not found"}))
    sys.exit(0)
except Exception as exc:
    print(json.dumps({"error": f"{type(exc).__name__}: {exc}"}))
    sys.exit(0)


def keys(value):
    return value if isinstance(value, list) else []


summary = {
    "sources": [
        {
            "id": s.get("id"),
            "type": s.get("type"),
            "api_base": s.get("api_base"),
            "key": mask((s.get("key") or [""])[0]),
        }
        for s in keys(cfg.get("provider_sources"))
    ],
    "models": [
        {
            "id": p.get("id"),
            "model": p.get("model"),
            "source": p.get("provider_source_id"),
            "enable": p.get("enable"),
        }
        for p in keys(cfg.get("provider"))
    ],
    "platforms": [
        {"id": p.get("id"), "type": p.get("type"), "enable": p.get("enable")}
        for p in keys(cfg.get("platform"))
    ],
    "plugins_enabled": cfg.get("plugin_set"),
    "wake_prefix": cfg.get("wake_prefix"),
    "admins": cfg.get("admins_id"),
    "dashboard": {
        "enable": (cfg.get("dashboard") or {}).get("enable"),
        "username": (cfg.get("dashboard") or {}).get("username"),
        "host": (cfg.get("dashboard") or {}).get("host"),
        "port": (cfg.get("dashboard") or {}).get("port"),
        "has_password": bool(
            (cfg.get("dashboard") or {}).get("password")
            or (cfg.get("dashboard") or {}).get("pbkdf2_password")
        ),
    },
}
print(json.dumps(summary, ensure_ascii=False))
"""


def inspect_config(name: str) -> dict:
    """Read AstrBot's config inside the container. Read-only.

    Any failure is returned as a dict with an "error" key so callers can
    degrade gracefully rather than crash the status report.
    """
    try:
        r = subprocess.run(
            [
                "docker",
                "exec",
                name,
                "python3",
                "-c",
                _INSPECT_SCRIPT,
                CONFIG_IN_CONTAINER,
            ],
            capture_output=True,
            text=True,
            timeout=20,
        )
    except Exception as exc:
        return {"error": f"{type(exc).__name__}: {exc}"}

    if r.returncode != 0:
        return {"error": (r.stderr or "inspection failed").strip()[:200]}

    try:
        return json.loads(r.stdout.strip().splitlines()[-1])
    except Exception as exc:
        return {"error": f"unparsable output: {exc}"}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


@click.group(invoke_without_command=True)
@click.pass_context
def cli(ctx):
    """AstrBot — minimal deployment helper. Deploy only, never configures."""
    if ctx.invoked_subcommand is None:
        click.echo(ctx.get_help())


@cli.command("setup-env")
@click.option("--password", default=None, help="Dashboard password (omit to generate)")
@click.option("--tag", default=None, help="Image tag, e.g. v4.26.2 (default: latest)")
@click.option(
    "--volume",
    default=None,
    help="Compose volume name; point at an existing volume to adopt its data",
)
def setup_env(password, tag, volume):
    """Generate .env with a dashboard password and optional overrides."""
    data = read_env()

    if password:
        problem = password_problem(password)
        if problem:
            click.secho(f"Password rejected: {problem}", fg=RED)
            sys.exit(1)
        data["ASTRBOT_DASHBOARD_PASSWORD"] = password
    elif data.get("ASTRBOT_DASHBOARD_PASSWORD"):
        click.echo("  [existing]  ASTRBOT_DASHBOARD_PASSWORD")
    else:
        generated = generate_password()
        data["ASTRBOT_DASHBOARD_PASSWORD"] = generated
        click.secho("  [generated] ASTRBOT_DASHBOARD_PASSWORD", fg=GREEN)
        click.secho(f"              {generated}", fg=CYAN)
        click.secho("  Save it now — it is only shown here.", fg=YELLOW)

    if tag:
        data["ASTRBOT_TAG"] = tag
    if volume:
        data["ASTRBOT_VOLUME"] = volume

    for key, default in (
        ("ASTRBOT_TAG", "latest"),
        ("ASTRBOT_CONTAINER", "astrbot"),
        ("ASTRBOT_PORT", "6185"),
        ("ASTRBOT_VOLUME", "astrbot_data"),
        ("TZ", "Asia/Shanghai"),
    ):
        data.setdefault(key, default)

    write_env(data)
    click.secho(f"\n.env written to {ENV_PATH}", fg=GREEN)
    if data["ASTRBOT_VOLUME"] != "astrbot_data":
        click.secho(
            f"  Volume: {data['ASTRBOT_VOLUME']} (adopting existing data)",
            fg=CYAN,
        )


@cli.command("up")
@click.option("--no-pull", is_flag=True, help="Skip the image pull step")
@click.option("--wait/--no-wait", default=True, help="Wait for the dashboard")
def up(no_pull, wait):
    """Pull the image and start AstrBot."""
    if not docker_available() or not compose_available():
        click.secho("Docker and Docker Compose are required.", fg=RED)
        sys.exit(1)

    if not ENV_PATH.exists():
        click.secho(".env not found — run: ./deploy.py setup-env", fg=YELLOW)
        sys.exit(1)

    env = read_env()
    name = container_name(env)
    port = env.get("ASTRBOT_PORT", "6185")

    generated = ensure_dashboard_password(env)
    if generated:
        click.secho(
            "\nDashboard password was missing or invalid — generated one:", fg=YELLOW
        )
        click.secho(f"  {generated}", fg=CYAN)
        click.secho(
            "  Applied only when AstrBot initialises a fresh volume; ignored\n"
            "  if the volume already holds a dashboard password.",
            fg=YELLOW,
        )

    if not no_pull:
        click.secho("Pulling image...", fg=YELLOW)
        _compose("pull")

    click.secho("Starting...", fg=YELLOW)
    if _compose("up", "-d").returncode != 0:
        click.secho("Startup failed. Check: ./deploy.py logs", fg=RED)
        sys.exit(1)

    if wait:
        if wait_for_dashboard(port):
            click.secho(f"\nDashboard ready: http://127.0.0.1:{port}", fg=GREEN)
        else:
            click.secho(
                f"\nContainer started but the dashboard did not answer on :{port}.",
                fg=YELLOW,
            )
            click.echo("  Inspect with: ./deploy.py logs")

    click.echo(f"\nContainer: {name}")
    click.echo("Next: open the dashboard, then configure providers, plugins and")
    click.echo("IM platforms there. This script does not manage that config.")


@cli.command("down")
@click.option(
    "--wipe",
    is_flag=True,
    help="ALSO DELETE THE DATA VOLUME (destroys credentials, platforms, sessions)",
)
@click.option("--yes", is_flag=True, help="Skip the confirmation prompt for --wipe")
def down(wipe, yes):
    """Stop AstrBot. Volumes are kept unless --wipe is given."""
    if wipe:
        click.secho(
            "WARNING: --wipe removes the data volume. This destroys the "
            "dashboard credentials, IM platform logins, the session "
            "database, workspaces and installed plugin state.",
            fg=RED,
            bold=True,
        )
        if not yes:
            click.confirm("Delete the volume as well?", abort=True)
        _compose("down", "-v")
        click.secho("Container and volume removed.", fg=YELLOW)
    else:
        _compose("down")
        click.secho("Container removed. Volume kept.", fg=GREEN)


@cli.command("status")
@click.option("--json", "as_json", is_flag=True, help="Emit machine-readable JSON")
def status(as_json):
    """Read-only health check and configuration summary."""
    env = read_env()
    name = container_name(env)
    port = env.get("ASTRBOT_PORT", "6185")

    running = container_running(name)
    reachable = http_ok(port) if running else False
    info = inspect_config(name) if running else {"error": "container not running"}

    if as_json:
        click.echo(
            json.dumps(
                {
                    "container": name,
                    "running": running,
                    "dashboard_reachable": reachable,
                    "port": port,
                    "image": env.get("ASTRBOT_TAG", "latest"),
                    "volume": env.get("ASTRBOT_VOLUME", "astrbot_data"),
                    "config": info,
                },
                ensure_ascii=False,
                indent=2,
            )
        )
        return

    def ok(flag):
        return click.style("[OK]", fg=GREEN) if flag else click.style("[--]", fg=YELLOW)

    click.secho(f"AstrBot  ({COMPOSE_FILE.parent})", bold=True)
    click.echo(f"  {ok(running)} container `{name}` running")
    click.echo(f"  {ok(reachable)} dashboard reachable on :{port}")
    click.echo(f"  image tag: {env.get('ASTRBOT_TAG', 'latest')}"
               f"   volume: {env.get('ASTRBOT_VOLUME', 'astrbot_data')}")

    if "error" in info:
        click.echo()
        click.secho(f"  config not inspected: {info['error']}", fg=YELLOW)
        return

    dash = info.get("dashboard", {})
    click.echo()
    click.secho("Dashboard", fg=CYAN)
    click.echo(
        f"  user={dash.get('username')}  host={dash.get('host')}"
        f"  port={dash.get('port')}  password_set={dash.get('has_password')}"
    )

    platforms = info.get("platforms") or []
    click.secho(f"IM platforms ({len(platforms)})", fg=CYAN)
    if not platforms:
        click.echo("  (none configured — AstrBot will not receive any messages)")
    for p in platforms:
        click.echo(f"  {p['id']}  type={p['type']}  enable={p['enable']}")

    sources = info.get("sources") or []
    click.secho(f"Provider sources ({len(sources)})", fg=CYAN)
    for s in sources:
        click.echo(
            f"  {s['id']}  type={s['type']}  api_base={s['api_base']}"
            f"  key={s['key']}"
        )

    models = info.get("models") or []
    click.secho(f"Models ({len(models)})", fg=CYAN)
    for m in models:
        click.echo(
            f"  {m['id']}  model={m['model']}  source={m['source']}"
            f"  enable={m['enable']}"
        )

    click.echo()
    click.echo(f"  wake_prefix={info.get('wake_prefix')}  admins={info.get('admins')}")
    click.echo(f"  plugins={info.get('plugins_enabled')}")


@cli.command("logs")
@click.option("-n", "--lines", default=50, help="Number of lines to show")
@click.option("-f", "--follow", is_flag=True, help="Follow log output")
def logs(lines, follow):
    """Tail container logs."""
    env = read_env()
    args = ["docker", "logs", "--tail", str(lines)]
    if follow:
        args.append("-f")
    args.append(container_name(env))
    subprocess.run(args)


@cli.command("shell")
def shell():
    """Open a shell inside the container."""
    env = read_env()
    subprocess.run(["docker", "exec", "-it", container_name(env), "bash"])


if __name__ == "__main__":
    cli()
